[workspace]
members = [
    "cargo",
]
resolver = "2"

[workspace.dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "60cb29c5e4f9772685c9873752196725c946a849" }

[workspace.metadata.dylint]
libraries = [
    { path = "cargo" },
]
